apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: ibm-common-service-operator-webhook-service
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    name: ibm-common-service-operator
status:
  loadBalancer: {}
